name: drawing_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  bloc: ^9.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  dio: ^5.7.0
  intl: ^0.19.0
  gap: ^3.0.1
  go_router: ^14.6.3
  get_it: ^8.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0



dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

